<?php
return array(
    '客户姓名' => 'CName',
    '联系方式' => 'Tel',
    '固定电话' => 'fixed',
    '所在小区' => 'Address',
    '面积' => 'Space',
    '户型' => 'huxing',
    '交房时间' => 'jiaofangtime',
    '量房时间' => 'liangfangtime',
    '装修方式' => 'Way',
    '来源渠道' => 'Channel',
    '业务员' => 'Userid',
    '设计师' => 'Designer',
    '咨询时间' => 'ConsultDate',
    '到店时间' => 'ComeTime',
    '签单时间' => 'OrderTime',
    '合同时间' => 'HetongTime',
    '定金金额' => 'Deposit',
    '合同金额' => 'OrdersValue',
    '业务员下次回访时间' => 'sremind',
    '设计师下次回访时间' => 'dremind',
    '工程监理下次回访时间' => 'premind',
    '效果图制图员' => 'xiaoguotu',
    '制图员' => 'Drawing',
    '材料员' => 'Material',
    '工程监理' => 'Project',
    '工长' => 'Captain',
    '开工时间' => 'StartTime',
    '竣工时间' => 'EndTime',
    '合同编号' => 'Number',
    '设计费' => 'shejifei',
    '服务费' => 'guanlifei',
    '轻辅费' => 'qingfu',
    '主材费' => 'zhucai',
    '第一次人工费' => 'once',
    '第二次人工费' => 'twice',
    '第三次人工费' => 'tirth',
    '其他费用' => 'others',
);
?>